// glow-presets-pro.js
//
// Glow Effects Pro: The Ultimate Preset Pack
// Version: 1.1.0
//
// Thank you for your purchase!
// This file contains over 20 professionally designed presets for the
// react-native-animated-glow-wrapper library.
//
// License: You are granted a license to use these presets in any number
// of personal and commercial projects. You may not, however, resell or
// redistribute this file.

export const glowPresetsPro = {
  // --- Energy & Action Presets ---

  // A fiery, flickering flame effect. Great for "hot" deals or destructive actions.
  hotFlame: {
    cornerRadius: 50,
    outlineWidth: 2,
    borderColor: '#ffffff',
    animationSpeed: 0.2,
    randomness: 0.2,
    outerGlowColors: ['#FFD700', '#FF8C00', '#FF4500', '#FFD700', '#FF8C00', '#FF4500'],
    outerGlowOpacity: 1,
    outerGlowDotSize: 40,
    outerGlowNumberOfOrbs: 16,
    outerGlowInset: 25,
    outerGlowSpeedMultiplier: 1.0,
    outerGlowScaleAmplitude: 2,
    outerGlowScaleFrequency: 2,
    innerGlowColors: ['#FFFFFF', '#FFD700'],
    innerGlowOpacity: 0.5,
    innerGlowDotSize: 20,
    innerGlowNumberOfOrbs: 25,
    innerGlowInset: 25,
    innerGlowSpeedMultiplier: 0.8,
    innerGlowScaleAmplitude: 2,
    innerGlowScaleFrequency: 8,
  },

  // A classic red and blue flashing siren effect.
  siren: {
    cornerRadius: 10,
    outlineWidth: 2,
    borderColor: 'white',
    animationSpeed: 0.7,
    randomness: 0.0,
    outerGlowColors: ['#ff3c00', '#ff3c00'],
    outerGlowOpacity: 1,
    outerGlowDotSize: 25,
    outerGlowNumberOfOrbs: 8,
    outerGlowInset: 0,
    outerGlowScaleAmplitude: 1,
    outerGlowScaleFrequency: 8,
    innerGlowColors: ['#00ffff', '#0044ff', '#ffffff'],
    innerGlowOpacity: 1,
    innerGlowDotSize: 25,
    innerGlowNumberOfOrbs: 7,
    innerGlowInset: 0,
    innerGlowSpeedMultiplier: 2,
    innerGlowScaleAmplitude: 1,
    innerGlowScaleFrequency: 8,
  },

  // A fast, chaotic effect for urgent alerts.
  alert: {
    cornerRadius: 10,
    outlineWidth: 2,
    borderColor: 'white',
    animationSpeed: 4,
    randomness: 0.01,
    outerGlowColors: ['#ff00bf', '#1100ff', '#ff6f00'],
    outerGlowOpacity: 0.7,
    outerGlowDotSize: 120,
    outerGlowNumberOfOrbs: 15,
    outerGlowInset: 33,
    outerGlowSpeedMultiplier: 1.0,
    outerGlowScaleAmplitude: 0,
    outerGlowScaleFrequency: 2.5,
    innerGlowColors: ['#44ff00', '#00ff84', '#ff6f00'],
    innerGlowOpacity: 1,
    innerGlowDotSize: 60,
    innerGlowNumberOfOrbs: 35,
    innerGlowInset: 25,
    innerGlowSpeedMultiplier: 1.0,
    innerGlowScaleAmplitude: 0,
    innerGlowScaleFrequency: 2.5,
  },

  // --- Cyberpunk & Retro Presets ---

  // A toxic green, bubbling neon effect.
  neonGreen: {
    cornerRadius: 50,
    outlineWidth: 2,
    borderColor: 'white',
    animationSpeed: 3,
    randomness: 0.01,
    outerGlowColors: ['#00ff84', '#ffff00', '#15ff00'],
    outerGlowOpacity: 0.45,
    outerGlowDotSize: 110,
    outerGlowNumberOfOrbs: 15,
    outerGlowInset: 33,
    outerGlowSpeedMultiplier: 1.0,
    outerGlowScaleAmplitude: 0.1,
    outerGlowScaleFrequency: 1,
    innerGlowColors: ['#44ff00', '#00ff84', '#96ff96'],
    innerGlowOpacity: 1,
    innerGlowDotSize: 60,
    innerGlowNumberOfOrbs: 35,
    innerGlowInset: 25,
    innerGlowSpeedMultiplier: 1,
    innerGlowScaleAmplitude: 0.1,
    innerGlowScaleFrequency: 1,
  },

  // A classic 80s vaporwave aesthetic with pink, cyan, and green.
  vaporwave: {
    cornerRadius: 50,
    outlineWidth: 2,
    borderColor: 'white',
    animationSpeed: 0.2,
    randomness: 0.1,
    outerGlowColors: ['#FF71CE', '#01CDFE', '#05ffa1'],
    outerGlowOpacity: 1,
    outerGlowDotSize: 60,
    outerGlowNumberOfOrbs: 15,
    outerGlowInset: 30,
    outerGlowSpeedMultiplier: 1.0,
    outerGlowScaleAmplitude: 1,
    outerGlowScaleFrequency: 1,
    innerGlowColors: ['#FFFFFF', '#ffd700'],
    innerGlowOpacity: 0.5,
    innerGlowDotSize: 28,
    innerGlowNumberOfOrbs: 25,
    innerGlowInset: 19,
    innerGlowSpeedMultiplier: 0.8,
    innerGlowScaleAmplitude: 1,
    innerGlowScaleFrequency: 1,
  },

  // --- Sleek & Modern Presets ---

  // A beautiful, slow-moving sunset gradient.
  oceanSunset: {
    cornerRadius: 10,
    outlineWidth: 2,
    borderColor: 'white',
    animationSpeed: 0.6,
    randomness: 0.001,
    outerGlowColors: ['#ff00bf', '#1100ff', '#ff6f00'],
    outerGlowOpacity: 0.9,
    outerGlowDotSize: 100,
    outerGlowNumberOfOrbs: 25,
    outerGlowInset: 20,
    outerGlowSpeedMultiplier: 1.0,
    outerGlowScaleAmplitude: 0,
    outerGlowScaleFrequency: 2.5,
    innerGlowColors: ['#ff00bf', '#33ccff', '#ff6f00', '#ffffff'],
    innerGlowOpacity: 1,
    innerGlowDotSize: 30,
    innerGlowNumberOfOrbs: 65,
    innerGlowInset: 1,
    innerGlowSpeedMultiplier: 1.0,
    innerGlowScaleAmplitude: 0,
    innerGlowScaleFrequency: 2.5,
  },

  // A clean, pulsating white light. Perfect for minimalist designs or "new" item indicators.
  pureWhite: {
    cornerRadius: 60,
    outlineWidth: 4,
    borderColor: 'white',
    animationSpeed: 0.1,
    randomness: 0.01,
    outerGlowColors: ['#FFFFFF'],
    outerGlowOpacity: 0.2,
    outerGlowDotSize: 120,
    outerGlowNumberOfOrbs: 15,
    outerGlowInset: 30,
    outerGlowSpeedMultiplier: 1,
    outerGlowScaleAmplitude: 0,
    outerGlowScaleFrequency: 1,
    innerGlowColors: ['#FFFFFF'],
    innerGlowOpacity: 1,
    innerGlowDotSize: 110,
    innerGlowNumberOfOrbs: 20,
    innerGlowInset: 48,
    innerGlowSpeedMultiplier: 1,
    innerGlowScaleAmplitude: 0,
    innerGlowScaleFrequency: 1,
  },

  // A fast, glittering marquee light effect. Great for "showtime" or premium features.
  showtime: {
    cornerRadius: 10,
    outlineWidth: 2,
    borderColor: 'white',
    animationSpeed: 0.01,
    randomness: 0.001,
    outerGlowColors: ['#ffe3a1', '#ffd700'],
    outerGlowOpacity: 0.9,
    outerGlowDotSize: 50,
    outerGlowNumberOfOrbs: 20,
    outerGlowInset: 10,
    outerGlowSpeedMultiplier: 10,
    outerGlowScaleAmplitude: 0.2,
    outerGlowScaleFrequency: 10,
    innerGlowColors: ['#ffffff', '#ffffff'],
    innerGlowOpacity: 1,
    innerGlowDotSize: 12,
    innerGlowNumberOfOrbs: 25,
    innerGlowInset: 0,
    innerGlowSpeedMultiplier: 10,
    innerGlowScaleAmplitude: 0.2,
    innerGlowScaleFrequency: 10,
  },
  
  // A default, vibrant rainbow effect for general use.
  defaultRainbow: {
    cornerRadius: 10,
    outlineWidth: 2,
    borderColor: 'white',
    animationSpeed: 0.7,
    randomness: 0.01,
    outerGlowColors: ['#00FFFF', '#FF00FF', '#FFFF00'],
    outerGlowOpacity: 0.15,
    outerGlowDotSize: 100,
    outerGlowNumberOfOrbs: 20,
    outerGlowInset: 15,
    outerGlowSpeedMultiplier: 1.0,
    outerGlowScaleAmplitude: 0,
    outerGlowScaleFrequency: 2.5,
    innerGlowColors: ['#00FFFF', '#FF00FF', '#FFFF00'],
    innerGlowOpacity: 0.3,
    innerGlowDotSize: 50,
    innerGlowNumberOfOrbs: 20,
    innerGlowInset: 15,
    innerGlowSpeedMultiplier: 1.0,
    innerGlowScaleAmplitude: 0,
    innerGlowScaleFrequency: 2.5,
  },

  // --- Themed Variations & Bonus Presets ---

  // A cool, pulsating blue flame or plasma arc. The energetic opposite of "hotFlame".
  plasmaArc: {
    cornerRadius: 50,
    outlineWidth: 2,
    borderColor: '#ffffff',
    animationSpeed: 0.2,
    randomness: 0.2,
    outerGlowColors: ['#00BFFF', '#8A2BE2', '#4169E1'],
    outerGlowOpacity: 1,
    outerGlowDotSize: 40,
    outerGlowNumberOfOrbs: 16,
    outerGlowInset: 25,
    outerGlowSpeedMultiplier: 1.0,
    outerGlowScaleAmplitude: 2,
    outerGlowScaleFrequency: 2,
    innerGlowColors: ['#FFFFFF', '#ADD8E6'],
    innerGlowOpacity: 0.5,
    innerGlowDotSize: 20,
    innerGlowNumberOfOrbs: 25,
    innerGlowInset: 25,
    innerGlowSpeedMultiplier: 0.8,
    innerGlowScaleAmplitude: 2,
    innerGlowScaleFrequency: 8,
  },

  // A successful, pulsing green light. Perfect for "confirm" or "success" states.
  confirmationGreen: {
    cornerRadius: 10,
    outlineWidth: 2,
    borderColor: 'white',
    animationSpeed: 1,
    randomness: 0.0,
    outerGlowColors: ['#32CD32', '#32CD32'],
    outerGlowOpacity: 1,
    outerGlowDotSize: 25,
    outerGlowNumberOfOrbs: 8,
    outerGlowInset: 0,
    outerGlowScaleAmplitude: 1,
    outerGlowScaleFrequency: 8,
    innerGlowColors: ['#98FB98', '#FFFFFF', '#32CD32'],
    innerGlowOpacity: 1,
    innerGlowDotSize: 25,
    innerGlowNumberOfOrbs: 7,
    innerGlowInset: 0,
    innerGlowSpeedMultiplier: 2,
    innerGlowScaleAmplitude: 1,
    innerGlowScaleFrequency: 8,
  },

  // A more subtle and beautiful warning than "alert".
  softWarning: {
    cornerRadius: 10,
    outlineWidth: 2,
    borderColor: 'white',
    animationSpeed: 2,
    randomness: 0.01,
    outerGlowColors: ['#FFD700', '#FFA500'],
    outerGlowOpacity: 0.7,
    outerGlowDotSize: 120,
    outerGlowNumberOfOrbs: 15,
    outerGlowInset: 33,
    outerGlowSpeedMultiplier: 1.0,
    outerGlowScaleAmplitude: 0,
    outerGlowScaleFrequency: 2.5,
    innerGlowColors: ['#FFFFFF', '#FFFACD'],
    innerGlowOpacity: 1,
    innerGlowDotSize: 60,
    innerGlowNumberOfOrbs: 35,
    innerGlowInset: 25,
    innerGlowSpeedMultiplier: 1.0,
    innerGlowScaleAmplitude: 0,
    innerGlowScaleFrequency: 2.5,
  },

  // A futuristic, hot pink neon effect.
  cyberPink: {
    cornerRadius: 50,
    outlineWidth: 2,
    borderColor: 'white',
    animationSpeed: 3,
    randomness: 0.01,
    outerGlowColors: ['#FF1493', '#FF00FF', '#DB7093'],
    outerGlowOpacity: 0.45,
    outerGlowDotSize: 110,
    outerGlowNumberOfOrbs: 15,
    outerGlowInset: 33,
    outerGlowSpeedMultiplier: 1.0,
    outerGlowScaleAmplitude: 0.1,
    outerGlowScaleFrequency: 1,
    innerGlowColors: ['#FFC0CB', '#FFFFFF'],
    innerGlowOpacity: 1,
    innerGlowDotSize: 60,
    innerGlowNumberOfOrbs: 35,
    innerGlowInset: 25,
    innerGlowSpeedMultiplier: 1,
    innerGlowScaleAmplitude: 0.1,
    innerGlowScaleFrequency: 1,
  },
  
  // A darker, more intense synthwave theme with deep purples and blues.
  synthwaveRider: {
    cornerRadius: 50,
    outlineWidth: 2,
    borderColor: 'white',
    animationSpeed: 0.2,
    randomness: 0.1,
    outerGlowColors: ['#DA70D6', '#9400D3', '#4B0082'],
    outerGlowOpacity: 1,
    outerGlowDotSize: 60,
    outerGlowNumberOfOrbs: 15,
    outerGlowInset: 30,
    outerGlowSpeedMultiplier: 1.0,
    outerGlowScaleAmplitude: 1,
    outerGlowScaleFrequency: 1,
    innerGlowColors: ['#FF69B4', '#EE82EE'],
    innerGlowOpacity: 0.5,
    innerGlowDotSize: 28,
    innerGlowNumberOfOrbs: 25,
    innerGlowInset: 19,
    innerGlowSpeedMultiplier: 0.8,
    innerGlowScaleAmplitude: 1,
    innerGlowScaleFrequency: 1,
  },

  // A mystical, deep space effect with purples and dark blues.
  cosmicNebula: {
    cornerRadius: 10,
    outlineWidth: 2,
    borderColor: 'white',
    animationSpeed: 0.6,
    randomness: 0.001,
    outerGlowColors: ['#483D8B', '#8A2BE2', '#9370DB'],
    outerGlowOpacity: 0.9,
    outerGlowDotSize: 100,
    outerGlowNumberOfOrbs: 25,
    outerGlowInset: 20,
    outerGlowSpeedMultiplier: 1.0,
    outerGlowScaleAmplitude: 0,
    outerGlowScaleFrequency: 2.5,
    innerGlowColors: ['#E6E6FA', '#D8BFD8', '#483D8B'],
    innerGlowOpacity: 1,
    innerGlowDotSize: 30,
    innerGlowNumberOfOrbs: 65,
    innerGlowInset: 1,
    innerGlowSpeedMultiplier: 1.0,
    innerGlowScaleAmplitude: 0,
    innerGlowScaleFrequency: 2.5,
  },

  // A luxurious, pulsating golden aura for premium items or user profiles.
  goldenAura: {
    cornerRadius: 60,
    outlineWidth: 4,
    borderColor: '#FFD700',
    animationSpeed: 0.1,
    randomness: 0.01,
    outerGlowColors: ['#FFD700'],
    outerGlowOpacity: 0.2,
    outerGlowDotSize: 120,
    outerGlowNumberOfOrbs: 15,
    outerGlowInset: 30,
    outerGlowSpeedMultiplier: 1,
    outerGlowScaleAmplitude: 0,
    outerGlowScaleFrequency: 1,
    innerGlowColors: ['#FFFFE0', '#F0E68C'],
    innerGlowOpacity: 1,
    innerGlowDotSize: 110,
    innerGlowNumberOfOrbs: 20,
    innerGlowInset: 48,
    innerGlowSpeedMultiplier: 1,
    innerGlowScaleAmplitude: 0,
    innerGlowScaleFrequency: 1,
  },

  // A glittering, magical effect with forest greens and a touch of gold.
  enchantedForest: {
    cornerRadius: 10,
    outlineWidth: 2,
    borderColor: 'white',
    animationSpeed: 0.01,
    randomness: 0.001,
    outerGlowColors: ['#2E8B57', '#66CDAA', '#DAA520'],
    outerGlowOpacity: 0.9,
    outerGlowDotSize: 50,
    outerGlowNumberOfOrbs: 20,
    outerGlowInset: 10,
    outerGlowSpeedMultiplier: 10,
    outerGlowScaleAmplitude: 0.2,
    outerGlowScaleFrequency: 10,
    innerGlowColors: ['#98FB98', '#FFFFFF'],
    innerGlowOpacity: 1,
    innerGlowDotSize: 12,
    innerGlowNumberOfOrbs: 25,
    innerGlowInset: 0,
    innerGlowSpeedMultiplier: 10,
    innerGlowScaleAmplitude: 0.2,
    innerGlowScaleFrequency: 10,
  },

  // A soft, gentle rainbow of pastel colors.
  pastelDream: {
    cornerRadius: 10,
    outlineWidth: 2,
    borderColor: 'white',
    animationSpeed: 0.7,
    randomness: 0.01,
    outerGlowColors: ['#FFB6C1', '#ADD8E6', '#98FB98', '#FFFFE0'],
    outerGlowOpacity: 0.15,
    outerGlowDotSize: 100,
    outerGlowNumberOfOrbs: 20,
    outerGlowInset: 15,
    outerGlowSpeedMultiplier: 1.0,
    outerGlowScaleAmplitude: 0,
    outerGlowScaleFrequency: 2.5,
    innerGlowColors: ['#FFC0CB', '#E0FFFF', '#F0FFF0'],
    innerGlowOpacity: 0.3,
    innerGlowDotSize: 50,
    innerGlowNumberOfOrbs: 20,
    innerGlowInset: 15,
    innerGlowSpeedMultiplier: 1.0,
    innerGlowScaleAmplitude: 0,
    innerGlowScaleFrequency: 2.5,
  },

  // A cold, slow-breathing ice effect. Great for "frozen" states or winter themes.
  arcticFreeze: {
    cornerRadius: 60,
    outlineWidth: 4,
    borderColor: 'white',
    animationSpeed: 0.08,
    randomness: 0.01,
    outerGlowColors: ['#00FFFF', '#E0FFFF'],
    outerGlowOpacity: 0.2,
    outerGlowDotSize: 120,
    outerGlowNumberOfOrbs: 15,
    outerGlowInset: 30,
    outerGlowSpeedMultiplier: 1,
    outerGlowScaleAmplitude: 0,
    outerGlowScaleFrequency: 1,
    innerGlowColors: ['#FFFFFF', '#AFEEEE'],
    innerGlowOpacity: 1,
    innerGlowDotSize: 110,
    innerGlowNumberOfOrbs: 20,
    innerGlowInset: 48,
    innerGlowSpeedMultiplier: 1,
    innerGlowScaleAmplitude: 0,
    innerGlowScaleFrequency: 1,
  },
};